### PR TITLE
makefile: few tweaks

### PR DESCRIPTION
**Pull request by macmpi**
no new feature, mostly editorial cleanup & word-smiting.
...ah, well, also incidentally used `install` in launcher section... :angel:

### CODE REVIEW

**Comment by mike632t** [comment]
> ...ah, well, also incidentally used `install` in launcher section... 

At least it wasn't accidentally!  Will test later..

**Comment by macmpi** [comment]
BTW, and due the first user issue, I think we should remove voyager models from  quick/sample list (until voyager rom distribution is eventually resolved).
Indeed, as these models require more attention, we should not drive users to a shortcut with error-prone usecase...

If we therefore shorten that quick/sample list, we can add some more, including some financial ones.
Thoughts?

**Review by mike632t — APPROVED** [review]

**Comment by macmpi** [comment]
Thanks.
Thoughts about removing voyager models in quicklist (and filling-in with some other models)?
(Will try to look at Tru64 side install)

**Comment by mike632t** [comment]
Can the flatpak build process pull in the missing ROM files using wget ?

**Pull request merged**
