### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by jonakeys**
This pull request adds support for FreeBSD in the same way as NetBSD already has.

### CODE REVIEW

**Review by mike632t — CHANGES_REQUESTED** [review]
Neat - Thank you for taking to time to test this an submit these changes, adding support for more platforms is always a good thing!

Could I ask that you add your OS and compiler version to the list of  tested platforms in the README.md ?   (Or just let me know what versions you are using and I'll add it.)

If you don't manage to reply by tomorrow evening I'll merge this change with the testing branch anyway..

**Comment by jonakeys** [comment]
Sure, I'll add the requested info to the README.md Although I found out not all calculators work. So next to the item of the shortcut keys I'll try to figure out the culprit and try to fix that.

**Comment by mike632t** [comment]
Short cut keys should now 'work' more as you expect on the 15C and 11C, though it was more of a design decision than something not working.

**Comment by jonakeys** [comment]
> Sure, I'll add the requested info to the README.md Although I found out not all calculators work. So next to the item of the shortcut keys I'll try to figure out the culprit and try to fix that.

The segmentation faults I encountered earlier are now resolved with the added support the shortcut keys.

**Comment by mike632t** [comment]
If the problem is sorted can you close this issue?

**Pull request merged**
